### ISSUE TITLE
Expose server reachability

### ISSUE THREAD

**Issue by hhoffstaette** [SuperQ/chrony_exporter#75]
Based on a [recent mailing list thread](https://listengine.tuxfamily.org/chrony.tuxfamily.org/chrony-users/2024/04/msg00010.html) I'd like to propose the exposure of an additional metric.

The original chrony client shows the [reachability of upstream servers](https://gitlab.com/chrony/chrony/-/blob/master/client.c?ref_type=heads#L2095) and this can be used to detect changes in network topology without having to rely on time/clock drift for failure detection.

Having this field exposed would make it easy to create e.g. an alertmanager rule.

**Comment by SuperQ** [comment]
From the [chrony docs](https://chrony-project.org/doc/4.4/chronyc.html)

> This shows the source’s reachability register printed as an octal number. The register has 8 bits and is updated on every received or missed packet from the source. A value of 377 indicates that a valid reply was received for all from the last eight transmissions.

The [facebook/time](https://pkg.go.dev/github.com/facebook/time@v0.0.0-20240418133307-0d7d0698529e/ntp/chrony#SourceData) library returns this value as a uint16.

While there's some interesting things we could do with the bits, the most useful thing that comes to mind would be to compute the ratio of 1 to 0 bits in the value as a ratio. So if all probes fail the metrics is 0.0. If all probes are passing, 1.0. 

Another option would be to only expose the current bit, since Prometheus is polling typically faster than NTP packets are sent, we could represent the "last reach success" as a simple bool.

The question is, how is that register updated, shift left? shift right?

The next useful option would be to expose the bits directly as a state set. While this would provide the full bit detail, it's a bit high cardinality.

As for the easy option, exposing the raw byte directly as a value, this seems less useful for monitoring, as you would have to interpret the bits in PromQL for the alert to be useful. I would say this is better mapped in the exporter's code.

**Comment by hhoffstaette** [comment]
The reachability is [available](https://github.com/facebook/time/blob/0d7d0698529ece58709552ad595ea38409078d74/ntp/chrony/packet.go#L382) in the SourceData.
However I now wonder if this is more useful/better than just alerting on `chrony_sources_state_info` which already exposes the source state in a human-readable way.

**Comment by hhoffstaette** [comment]
Flattening the value to a binary `last_reach_success` is probably too fragile against network hiccups - packets can and do get lost even on inhouse networks (resync, reboots and whatnot).

Hmm.. maybe this wasn't such a useful idea at all :sweat_smile:

**Comment by SuperQ** [comment]
Chrony's default `minpoll` is 6, which is 2^6 seconds (64 seconds) with a `maxpoll` of 10 (2^10 = 1024 seconds). So even if you have a scrape interval of 60s, you'll always catch the last reach bit.

**Comment by SuperQ** [comment]
Did some local testing.
* The iburst means there are a number of packets on restart, so we can't catch individual early bits.
* The ratio of course starts out at 0 on restart, so you can't alert on the success ratio until it's been up until it fills up the bits.
